var tree = [["Goetas",,"",
                [["XML",,"",
                [["XSDReader","Goetas\/XML\/XSDReader.html","",
                [["Exception","Goetas\/XML\/XSDReader\/Exception.html","",
                [["IOException","Goetas\/XML\/XSDReader\/Exception\/IOException.html"," < Exception",
                [        ]],["TypeException","Goetas\/XML\/XSDReader\/Exception\/TypeException.html"," < Exception",
                [        ]]        ]],["Schema","Goetas\/XML\/XSDReader\/Schema.html","",
                [["Attribute","Goetas\/XML\/XSDReader\/Schema\/Attribute.html","",
                [["Attribute","Goetas\/XML\/XSDReader\/Schema\/Attribute\/Attribute.html","",
                [        ]],["AttributeGroup","Goetas\/XML\/XSDReader\/Schema\/Attribute\/AttributeGroup.html","",
                [        ]],["AttributeHolder","Goetas\/XML\/XSDReader\/Schema\/Attribute\/AttributeHolder.html","",
                [        ]],["AttributeReal","Goetas\/XML\/XSDReader\/Schema\/Attribute\/AttributeReal.html"," < TypeNodeChild",
                [        ]]        ]],["Element","Goetas\/XML\/XSDReader\/Schema\/Element.html","",
                [["Element","Goetas\/XML\/XSDReader\/Schema\/Element\/Element.html","",
                [        ]],["ElementHolder","Goetas\/XML\/XSDReader\/Schema\/Element\/ElementHolder.html","",
                [        ]],["ElementNode","Goetas\/XML\/XSDReader\/Schema\/Element\/ElementNode.html"," < TypeNodeChild",
                [        ]],["ElementReal","Goetas\/XML\/XSDReader\/Schema\/Element\/ElementReal.html"," < TypeNodeChild",
                [        ]],["Group","Goetas\/XML\/XSDReader\/Schema\/Element\/Group.html","",
                [        ]]        ]],["Exception","Goetas\/XML\/XSDReader\/Schema\/Exception.html","",
                [["SchemaException","Goetas\/XML\/XSDReader\/Schema\/Exception\/SchemaException.html"," < Exception",
                [        ]],["TypeNotFoundException","Goetas\/XML\/XSDReader\/Schema\/Exception\/TypeNotFoundException.html"," < SchemaException",
                [        ]]        ]],["Inheritance","Goetas\/XML\/XSDReader\/Schema\/Inheritance.html","",
                [["Base","Goetas\/XML\/XSDReader\/Schema\/Inheritance\/Base.html","",
                [        ]],["Extension","Goetas\/XML\/XSDReader\/Schema\/Inheritance\/Extension.html"," < Base",
                [        ]],["Restriction","Goetas\/XML\/XSDReader\/Schema\/Inheritance\/Restriction.html"," < Base",
                [        ]]        ]],["Type","Goetas\/XML\/XSDReader\/Schema\/Type.html","",
                [["BaseComplexType","Goetas\/XML\/XSDReader\/Schema\/Type\/BaseComplexType.html"," < Type",
                [        ]],["ComplexType","Goetas\/XML\/XSDReader\/Schema\/Type\/ComplexType.html"," < BaseComplexType",
                [        ]],["ComplexTypeSimpleContent","Goetas\/XML\/XSDReader\/Schema\/Type\/ComplexTypeSimpleContent.html"," < BaseComplexType",
                [        ]],["SimpleType","Goetas\/XML\/XSDReader\/Schema\/Type\/SimpleType.html"," < Type",
                [        ]],["Type","Goetas\/XML\/XSDReader\/Schema\/Type\/Type.html","",
                [        ]],["TypeNodeChild","Goetas\/XML\/XSDReader\/Schema\/Type\/TypeNodeChild.html","",
                [        ]]        ]],["Schema","Goetas\/XML\/XSDReader\/Schema\/Schema.html","",
                [        ]],["SchemaItem","Goetas\/XML\/XSDReader\/Schema\/SchemaItem.html","",
                [        ]]        ]],["Utils","Goetas\/XML\/XSDReader\/Utils.html","",
                [["UrlUtils","Goetas\/XML\/XSDReader\/Utils\/UrlUtils.html","",
                [        ]]        ]],["SchemaReader","Goetas\/XML\/XSDReader\/SchemaReader.html","",
                [        ]]        ]]        ]]        ]]        ]

